pool:
  name: Azure Pipelines
steps:
- task: HelmInstaller@0
  displayName: 'Install Helm latest'
  inputs:
    helmVersion: '2.14.1'
    installKubectl: true
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts: drop'
