apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: azurefile
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: managed-premium
    resources:
        requests:
            storage: 1Gi
